### ISSUE TITLE
AE2 autocrafting + gregtech tools

### ISSUE THREAD

**Issue by Vliro** [JasonMcRay/InfiTech-1.7#507] opened 2016-03-13 15:10 UTC
Was running the latest ftb version and just downloaded off github, when suddenly AE2 autocrafting completely broke with GT tools. I tried to reset the patterns and use/not use the substitution feature. Also tried change to earliest rv3 beta 1, nothing really works. Requests to craft ridonculous amounts of tools in order to do even the simplest recipes. It worked up until changing to the latest, that is using the appropriate amount of tools and/or durability.
![untitled](https://cloud.githubusercontent.com/assets/8606465/13729469/04e8d8d8-e936-11e5-9b12-47c6f1110376.png)

**Comment by JasonMcRay** [comment] 2016-03-13 15:16
You need to use new substitution mode when coding patterns

**Comment by Vliro** [comment] 2016-03-13 15:18
I redid my patterns, and now it uses the tools that have lower durability as well, but it still requests a lot of them.

**Comment by JasonMcRay** [comment] 2016-03-13 15:22
Something you must be doing wrong...
![2016-03-13_16 19 45](https://cloud.githubusercontent.com/assets/4236895/13729548/a47bddb8-e937-11e5-864a-aa29ec2859c3.png)

**Comment by JasonMcRay** [comment] 2016-03-13 15:23
Try also to grab the latest AE2 RV3 beta 5, thats what I am using

**Comment by Vliro** [comment] 2016-03-13 15:28
Hmm, perhaps it is because I am using my old map from the previous version. I cloned the repo today so I am using the latest AE2. It still requests a lot of tools, I'll try again in a flat world, but everytime I exit a map I have to restart minecraft.

**Comment by JasonMcRay** [comment] 2016-03-13 15:32
It should not matter if you are using old map or not. I have my test world created in early 3.1 (maybe even sooner). The bug with not being able to rejoin the world is known issue awaiting a fix:
https://github.com/JasonMcRay/InfiTech-1.7/issues/498

**Comment by Vliro** [comment] 2016-03-13 15:44
It seemed just redoing the entire autocrafting setup entirely fixed the problem. Though(dunno if it was like this before) if you have more than 1 hammer it requests everyone, but if I only have 1 hammer it uses that one, since I now have 21 cobalt hammers.

**Comment by JasonMcRay** [comment] 2016-03-13 15:54
Yea it seems like it requests more tools if they are available. However it uses the durability on each, so it is splitting the damage taken from crafting. Not a big deal. however i just reported it, to hear if it is intended or a bug.

**Comment by Vliro** [comment] 2016-03-13 16:10
If it uses the durability on each then it is indeed a problem. I just moved my 20 excess hammers to a chest in the meantime.

**Comment by JasonMcRay** [comment] 2016-03-13 16:57
It uses on each, but not at the same time. It uses durability on 1st, then next crafting on 2nd, and so on.

**Comment by JasonMcRay** [comment] 2016-03-22 15:16
Going to close this as intended behaviour. But just in case linking the raised issue about the using more tools (and splitting the damage between them) for future reference:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2191

**Closed** 2016-03-22 15:16 UTC
Labels: Intended Behavior
