### ISSUE TITLE
crash, index out of bounds, maybe backpack

### ISSUE THREAD

**Issue by ghoulsblade** [JasonMcRay/InfiTech-1.7#432] opened 2015-11-24 20:12 UTC
at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
might be related to backpacks, as i always carry some, but just a suspicion on my side, no evidence for that yet.
Didnt get any crashes in the last few months, but thats the 3rd time it crashed since .20 so i thought i'd upload the logs :)
Keep up the good work!

[crash-2015-11-24_21.05.42-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/43172/crash-2015-11-24_21.05.42-client.txt)
[crash-2015-11-22_15.07.41-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/43173/crash-2015-11-22_15.07.41-client.txt)
[crash-2015-11-22_13.23.46-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/43174/crash-2015-11-22_13.23.46-client.txt)

**Comment by JasonMcRay** [comment] 2015-11-24 20:19
Is the crash happening just like that, or after you for example try to open any gui or backpack or click on something.

**Comment by ghoulsblade** [comment] 2015-11-24 23:08
no specific pattern that i'm aware of. game hangs a while, then closes while opening a chest.

**Comment by JasonMcRay** [comment] 2015-11-24 23:42
I spent 2hrs trying to crash myself somehow with backpacks. Tried to gather information in diferent places but the crash is too broad. Sometimes it was Waila, Buildcraft, Forestry and other mods... So I will need as much information as possible.

If you will manage to recreate the crash at least 2times in a row, provide an exact steps, exact contents of your inventory (screenshot the best) we can try to solve that.

**Comment by ghoulsblade** [comment] 2015-11-25 09:24
Will do, but its fairly rare, so i dont know how to reproduce it reliably yet.

I'm an experienced programmer, just not working much with java IDEs lately aside from some simple App dev. I did mess around with minecraft modding a while ago, so i know my way around the code a bit, but i dont have that much experience with in-depth eclipse debugging.
If you can point me in the right direction i can try and figure out the details myself :)
Is there a way with eclipse / JDK to record a sort of function call trace that would allow listing all the methods called within the last few seconds, or a way to save the current state when an exception to a file so i can send it to you for inspection when i get the crash during while having a debug environment running ?

**Comment by JasonMcRay** [comment] 2015-11-25 09:29
Cant help with that personally. Being a pack dev does not necessary mean I know Java :( Maybe someone like @Blood-Asp could point you some direction :)

**Comment by JasonMcRay** [comment] 2015-11-25 09:39
Also I have found that beyond reality had same crash, but not sure if the cause is the same. @Dominance sorry to ping, but can you share little insight what can be the cause? As i said, I am not a programmer, so I have honestly no idea in this matter. What was the cause in BR?

**Comment by ghoulsblade** [comment] 2015-11-28 00:45
Dont waste time on it for now, its too rare to be really annoying. Lets see what info adds up in here first.
I just had it again, while rclicking enderchest with backpack at a short lagspike from the server, rclicking 2-3 times with the backpack in empty air afterwards as it didnt react, then it crashed after about 5 seconds standstill. Mousewheel was moved to select the backpack in hotbar as well, not sure if that plays a role.
So far it looks to me that the crash only happens when trying repeatedly to open a backpack during a lagspike from the server (e.g. internet connection hickup, or some non-minecraft related backup job or similar starting on the server)

**Comment by JasonMcRay** [comment] 2015-11-28 17:44
Well lets. See what Forestry devs will have to say about it...
https://github.com/ForestryMC/ForestryMC/issues/988

**Comment by JasonMcRay** [comment] 2015-12-27 22:42
@ghoulsblade there has been some changes in Forestry networking, can you please do some testing with the latest modpack (.22) to see if the issue is still present? Thanks

**Comment by ghoulsblade** [comment] 2015-12-28 12:04
cant reproduce the crash intentionally aside from hours of normal play, i'm mostly on groves server atm, i'll report if i get it again after he upgrades, havent seen it in a while tho. might have been specific to network spikes on the private server i was on earlier.

**Comment by JasonMcRay** [comment] 2016-01-18 13:53
Looks like its fixed in latest forestry

**Closed by JasonMcRay** 2016-01-18 13:53 UTC
Labels: help wanted, Mod Bug, Reported to Mod Developers
