### ISSUE TITLE
Fluxed Electrum Dust decomposes to Cellulose

### ISSUE THREAD

**Issue by pyure** [JasonMcRay/InfiTech-1.7#128] opened 2015-01-16 23:15 UTC
The minechem decomposer currently reduces Fluxed Electrum Dust to cellulose.  I can't imagine this is intentional.

Electrum also decomposes to cellulose on the server, although I swear I saw it decompose to gold, silver, copper and iron oxide in single player (I can't seem to replicate that)

There's a short delay as the Decomposer recipe shows up in NEI for Electrum Dust.  It stalled my client for 2 minutes the first time I brought it up, and then I killed the client, but I cannot replicate that.  This one's just an FYI in case anyone else reports it.

**Comment by pyure** [comment] 2015-01-17 13:30
I'm noticing other resources decompose to cellulose that probably shouldn't.  Each time, there's a small delay before the recipe loads.  I'll note some specific examples if/when I find them.

**Comment by JasonMcRay** [comment] 2015-01-17 17:31
As for decomposer delay with NEI recipes: Yes it will happen from time to time, because the decomposer is trying to get the correct material list for the decomposition. (Decomposer recipes arent hardcoded, they rely on crafting recipes mostly)

As for the Electrum => Cellulose... having a look into it right now

**Comment by JasonMcRay** [comment] 2015-01-17 17:54
Ok.... Most of the GT dusts are decomposing to cellulose.
https://github.com/jakimfett/Minechem/issues/583

**Comment by pyure** [comment] 2015-01-18 17:33
Yeah I noticed that, was about to post it.  Interesting.  It must be a default of some sort.

**Comment by hlaaftana** [comment] 2015-01-19 22:36
The cause is minechem sees the GT dusts as crafted with a GT hammer and crushed ore. The mod sees the stick in the hammer, so it outputs cellulose. This might not be the cause if the dusts only output cellulose, though. I'm seriously tired so I'm too lazy to check right now.

**Comment by hlaaftana** [comment] 2015-01-19 22:44
If my theory is true, either you should blacklist all GT dusts or the MChem team should add mod recipes as coded recipes instead of crafting reliant ones. The first one is the easiest one to do, isn't it?

**Comment by JasonMcRay** [comment] 2015-01-19 23:54
Yes the first one is easiest to do. I could make a Minetweaker scripts for it but... it is gonna be annoying to add it for ALL the dusts. If someone will want to take care of this... feel free to make a PR for it :)

**Comment by JasonMcRay** [comment] 2015-01-20 00:01
Or I will do it over-time :)

**Comment by pyure** [comment] 2015-01-21 15:01
I think this is a good plan Jason.  If the players want to bitch and complain about dusts they wish to decompose, they can work out a balanced decomposition script and recommend it for addition.

**Comment by JasonMcRay** [comment] 2015-01-26 19:37
I am going to close this issue. GT dusts will not be Synthesizable or Decomposable in InfiTech 2. But I will take the time to do it for IT:R (and maybe will push it into IT:2). Still proposition for anyone wanting to take this task on themselves is still open :)

**Closed by JasonMcRay** 2015-01-26 19:37 UTC
Labels: help wanted, On Hold
