### ISSUE TITLE
Missing AE quartz seed recipes

### ISSUE THREAD

**Issue by Timeslice42** [JasonMcRay/InfiTech-1.7#289] opened 2015-07-12 18:07 UTC
The certus quartz, nether quartz, and fluix seed recipes are gone. At about line 368 (of AE2.zs) the recipes are removed, but they are never added back in. Fortunately in the mean time the assembler still has the recipe because it has all two item shapeless recipes, and it grabbed them before minetweaker removed them.

**Comment by DarknessShadow** [comment] 2015-07-12 19:42
lol i thought this was intended ...

**Comment by JasonMcRay** [comment] 2015-07-13 07:54
It is indeed intended to not be crafted manually. I wanted to make it craftable in Chemical Reactor, but I am unable to remove recipes from GT machines via Minetweaker. I will try to take a look onto disabling Assembler recipe and adding ChemR recipe.

Will tag this as wontfix, but will leave it open so I dont forget to take a look onto the recipe disabling.

**Closed** 2015-07-16 07:43 UTC
Labels: FIX ON DEV (will close upon release)
