### ISSUE TITLE
Thaumcraft Eldrich biome in overworld

### ISSUE THREAD

**Issue by bcg17** [JasonMcRay/InfiTech-1.7#242] opened 2015-06-23 15:07 UTC
I found an Eldrich biome in the overworld on my stream it does spawn Eldrich guardians and Pechs I think its the biome that makes up the Eldrich dimension but i have never been there so i cannot be sure.
Here's the links:

https://www.youtube.com/watch?v=4hWSxNWTQjM&feature=youtu.be

f3 screen since you see ti in the video:

http://imgur.com/eHJObPD

**Comment by AiwendilCiunio** [comment] 2015-06-23 16:09
Very interesting, although Eldritch dimension is like a labirynth, looks nothing like that. I have no idea what you have found, never heard of it :)

**Comment by JasonMcRay** [comment] 2015-06-23 16:30
its certainly interesting. This mostly is Biome ID conflict, but I checked and Eldritch Biome is ID195 and nothing else is set near close to that.

Reported to azanor:
https://github.com/Azanor/thaumcraft/issues/1812

**Comment by JasonMcRay** [comment] 2015-07-20 13:25
According to few ppl this "issue" is caused by minecraft itself with its shifted biome IDs. Because its not a gamebreaking issue I am going to close this and lets consider it as something occasionaly wierd and "intended"

**Closed by JasonMcRay** 2015-07-20 13:25 UTC
Labels: Reported to Mod Developers

**Comment by Timeslice42** [comment] 2016-03-23 21:59
I can confirm this issue still exists :P

https://i.imgur.com/SNW4fNu.jpg
