### ISSUE TITLE
Thaumcraft Infused Seeds infusion giving always Aer Seeds

### ISSUE THREAD

**Issue by Dlur100** [JasonMcRay/InfiTech-1.7#535] opened 2016-03-26 06:43 UTC
I'm attempting to infuse seeds with terra to get earth seeds from thaumic tinker.  When I place 4 terra shards down and start the infusion the process goes fine, but outputs aer seeds instead of terra seeds.

http://i.imgur.com/wIvjFT2.png

**Comment by JasonMcRay** [comment] 2016-03-26 14:07
Its actually happening with all infused seeds.

**Comment by JasonMcRay** [comment] 2016-03-26 14:12
Reported: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/847

Will try to make a workaround fix with MT scripts

**Comment by JasonMcRay** [comment] 2016-03-26 14:33
@Xavion3 You are our Thaumcraft guys, so can you please take care of the workaround? Thanks

**Comment by Dlur100** [comment] 2016-03-26 16:25
Also, potentially related, maybe not.  Once I grow the aer seeds if I right-click on the mature crop it crashes my client each time.

**Comment by JasonMcRay** [comment] 2016-03-26 16:26
Crash log please

**Comment by Dlur100** [comment] 2016-03-26 17:03
[crash-2016-03-26_11.23.02-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/190548/crash-2016-03-26_11.23.02-client.txt)
[crash-2016-03-26_11.12.05-client.txt](https://github.com/JasonMcRay/InfiTech-1.7/files/190549/crash-2016-03-26_11.12.05-client.txt)

**Comment by JasonMcRay** [comment] 2016-03-26 20:57
Yea... That one is known: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/843

**Comment by Xavion3** [comment] 2016-03-26 21:42
Could probably get something working for the seeds if I tried but until we know how it's possible to harvest them it's probably easier to just disable them. Thoughts?

**Comment by Dlur100** [comment] 2016-03-27 00:36
FYI, I did use infused crops on the 3.1.x server just fine.

**Comment by Xavion3** [comment] 2016-03-27 01:04
I know they worked fine, I used them to great effect too, but something about 3.2 seems to have them being buggier, I've encountered issues with crashing on harvest while testing in a creative world.

**Comment by Timeslice42** [comment] 2016-03-27 03:34
I thought you said it was the missing aspects? Or did we fix that already?

**Comment by Xavion3** [comment] 2016-03-27 08:35
That's different but we hadn't done that yet, this seems to be a crash on all aspects.

**Comment by JasonMcRay** [comment] 2016-03-27 20:14
Anyway @Xavion3 I think good idea is just to disable these until they are fixed on TT side (at least the crash)

**Comment by JasonMcRay** [comment] 2016-03-28 14:32
So Infused seeds are disabled until its fixed.

**Comment by adamsonich** [comment] 2016-04-05 04:43
TT autor is out for 1.7.10 version as I see.
U need rollback TT version back to version without support Ender farm (It was my idea to join this two mods)
I pref 2.5-1.7.10-512 version

**Comment by Xavion3** [comment] 2016-04-05 05:28
If that's actually the cause we should be able to go as late as 517 as 518 on [here](http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/) was the significant change from what I can tell.

**Comment by adamsonich** [comment] 2016-04-05 06:00
Well. My pref is only my pref. I dont remember why i dont use v517. But yes v518 has ender io farm support.

**Comment by Xavion3** [comment] 2016-04-10 17:24
http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/

Just to make it easier to remember where the builds are posting the link here.

**Comment by Xavion3** [comment] 2016-04-12 15:46
```
// Fix Infused Crops
Research.orphanResearch("INFUSED_POTIONS");
Research.removeResearch("INFUSED_POTIONS");
Research.addResearch("GT_INFUSED_POTIONS", "TT_CATEGORY", "aqua 5, perditio 5", 7, -5, 2, <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "ignis"}]}}));
game.setLocalization("en_US", "tc.research_name.GT_INFUSED_POTIONS", "Infused Crops");
game.setLocalization("en_US", "tc.research_text.GT_INFUSED_POTIONS", "[TT] Who said bees? No one said bees.");
Research.addPrereq("GT_INFUSED_POTIONS", "BRIGHT_NITOR", false);
Research.addPrereq("GT_INFUSED_POTIONS", "INFUSION", true);
Infusion.removeRecipe(<ThaumicTinkerer:infusedSeeds>);
Infusion.addRecipe("GT_INFUSED_POTIONS", <minecraft:wheat_seeds>, [<Thaumcraft:ItemShard:6>, <Thaumcraft:ItemShard:6>, <Thaumcraft:ItemShard:6>, <Thaumcraft:ItemShard:6>], "meto 32, messis 32", <InfinityCore:infinityStone>, 5);
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "aer"}]}}), <InfinityCore:infinityStone>, "aer 8");
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "ignis"}]}}), <InfinityCore:infinityStone>, "ignis 8");
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "aqua"}]}}), <InfinityCore:infinityStone>, "aqua 8");
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "terra"}]}}), <InfinityCore:infinityStone>, "terra 8");
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "ordo"}]}}), <InfinityCore:infinityStone>, "ordo 8");
Crucible.addRecipe("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>.withTag({mainAspect: {Aspects: [{amount: 1, key: "perditio"}]}}), <InfinityCore:infinityStone>, "perditio 8");
Research.clearPages("GT_INFUSED_POTIONS");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.0");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.1");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.2");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.3");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.4");
Research.addPage("GT_INFUSED_POTIONS", "ttresearch.page.INFUSED_POTIONS.5");
Research.addInfusionPage("GT_INFUSED_POTIONS", <InfinityCore:infinityStone>);
Research.addCruciblePage("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedSeeds>);
Research.addCruciblePage("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedPotion:0>);
Research.addCruciblePage("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedPotion:1>);
Research.addCruciblePage("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedPotion:2>);
Research.addCruciblePage("GT_INFUSED_POTIONS", <ThaumicTinkerer:infusedPotion:3>);
```

Script bit here because it needs the proper temporary item from infinity core which I don't know the name of, just replace the infinity stone with it. This way I won't forget about this.

**Closed** 2016-04-12 18:32 UTC
Labels: Mod Bug, waiting for fix, Workaround fix
