### ISSUE TITLE
Connected Textures

### ISSUE THREAD

**Issue by DarknessShadow** [JasonMcRay/InfiTech-1.7#270] opened 2015-07-03 14:25 UTC
The enderio Facades dont have connected textures anymore In the newest version 3.1.2 
<a href="http://imgur.com/lHYKei9"><img src="http://i.imgur.com/lHYKei9.jpg" title="source: imgur.com" /></a>

**Comment by AiwendilCiunio** [comment] 2015-07-03 14:33
I can confirm that, before update it was fine.

**Comment by JasonMcRay** [comment] 2015-07-03 16:17
Is it for all blocks that have connected textures? or only for example with chisel blocks?

**Comment by AiwendilCiunio** [comment] 2015-07-03 19:33
hard to tell because I can't think of any non-chisel blocks that have connected textures. Other than glass, but that won't work with facades. Can you give me examples of such blocks so I can test them?

**Comment by JasonMcRay** [comment] 2015-07-03 19:34
extra utilities types of stone for example

**Comment by AiwendilCiunio** [comment] 2015-07-03 20:01
nope, ExU edged stone bricks don't connect either.

**Comment by DarknessShadow** [comment] 2015-07-03 21:34
The enderio facades do have connected textures with each other
<a href="http://imgur.com/cffdHdP"><img src="http://i.imgur.com/cffdHdP.jpg" title="source: imgur.com" /></a>

**Comment by JasonMcRay** [comment] 2015-07-06 14:17
Ok. Reported to eIO dev: https://github.com/SleepyTrousers/EnderIO/issues/2641

**Comment by JasonMcRay** [comment] 2015-07-06 14:37
Still happens with ExU. It has been reported while ago. https://github.com/rwtema/extrautilities/issues/462

**Comment by JasonMcRay** [comment] 2015-07-25 15:29
Looks like RWTema is not really looking at the reported issues that much :(. Gonna close this.

**Closed by JasonMcRay** 2015-07-25 15:29 UTC
Labels: minor, Reported to Mod Developers
